# Generated by Django 2.0.2 on 2018-02-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiche',
            old_name='programme',
            new_name='format',
        ),
        migrations.AddField(
            model_name='fiche',
            name='project_title',
            field=models.CharField(default='boubou', max_length=300),
            preserve_default=False,
        ),
    ]
