# Generated by Django 2.0.2 on 2018-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0002_auto_20180214_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
