# Generated by Django 2.0.2 on 2018-02-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0003_auto_20180214_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.Format'),
        ),
    ]
