# Generated by Django 2.0.2 on 2018-02-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0004_auto_20180214_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='custom_ref',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
