# Generated by Django 2.0.2 on 2018-02-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0005_auto_20180222_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche',
            name='budget',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fiche',
            name='description',
            field=models.TextField(blank=True, help_text='WYSIWYG', null=True),
        ),
    ]
